project: lenatrack
source:
  repoURL: 'https://github.com/deschery/vocabulary-service.git'
  path: dev
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: lenatrack
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
