apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocabulary-service
  labels:
    app: vocabulary-service
spec:
  replicas: 1
  template:
    metadata:
      name: vocabulary-service
      labels:
        app: vocabulary-service
    spec:
      containers:
        - name: vocabulary-service
          image: deschery/vocabulary-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: LENATRACK_CORS_ALLOWEDORIGINS
              value: http://eezhyzlax9zbrppr.myfritz.net/
      restartPolicy: Always

  selector:
    matchLabels:
      app: vocabulary-service

